### ISSUE TITLE
Deprecated function outputln and missing output

### ISSUE THREAD

**Issue by freestream** [albertdahlin/dahbug#3]
Looks like **outputln** is deprecated and you have according to your readme  introduced **output** to your class but when i look in your commit it looks more like it is **write** that is the new function. Could you maybe update your class or your readme so this wont be confusing? 

![screen shot 2015-01-28 at 08 14 31](https://cloud.githubusercontent.com/assets/5450032/5933829/2a47fb08-a6c6-11e4-86e6-78ec56167278.png)

**Comment by albertdahlin** [comment]
Thank you for pointing that out. I have corrected this now.
