### ISSUE TITLE
string_cap not presenting correcly in log with null byte

### ISSUE THREAD

**Issue by freestream** [albertdahlin/dahbug#5]
A string containing null bytes longer then the string_cap is presented in the log with "..." ending but the string is only containing the the strings value except the null bytes. This gets a bit confusing when you know the cap is set to a heigh number but the string looks to be cut or is some way manipulated in the unexpected way. In the result bellow I would not expect the string to have "..." just after the string value. It looks more to me that I could have another function before the dump that have added the "..." to the string. Would be better if the null bytes was presented in some way.

To reproduce:
string_cap = 100

$string = "teststring";
str_pad($string, 200, "\0");
dahbug::dump($string);

the output in the log will be
(string:200:ASCII) 'teststring...'

**Comment by albertdahlin** [comment]
I am going to add a proper string escaping for non printable chars output by dump.

**Comment by albertdahlin** [comment]
Closed by commit 6dd758236a7889f8577f0d8afb9cb3d806905697
